spring.application.name=deliveryboy

server.port=8090
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

#
#start kafka server command  = run kafka server : .\bin\windows\kafka-server-start.bat config\server.properties
